services:
  - type: web
    name: n8n-server
    env: docker
    plan: starter
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: NODE_ENV
        value: production
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
